name: Automated API tests and Lint using Postman CLI 

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Lint the spec
        run: |
          postman spec lint "a8458904-1dab-419c-8fee-eb8849afe339" --report-events 
      - name: Run API tests
        run: |
          postman collection run "52921466-e9cc692d-20f7-4a68-a51c-a9772806fa1f" -e \
          "52921466-22ce3f24-a0b7-4a09-9e8d-ec823f63ef2a" --report-events 
      
    